FROM python:3.9-buster

ENV PYTHONBUFFERED=1

WORKDIR /server

LABEL key = "Django container"

COPY requirements.txt requirements.txt

RUN pip3 install -r requirements.txt

COPY . .

CMD gunicorn server.wsgi:application --bind 0.0.0.0:8000

EXPOSE 8000