version: "3.9"
services:
  app:
    build: .
    volumes:
      - .:/server
    ports:
      - 8000:8000

    environment:
      DB_HOST: db
      DB_NAME: server
      DB_USER: postgres
      DB_PASS: postgres

    depends_on:
      - db
    image: application:django
    container_name: app_container
    command: >
      sh -c "python3 manage.py migrate &&
             python3 manage.py runserver 0.0.0.0:8000"


  db:
    image: postgres:15.0-alpine
    container_name: MoleDataBase_postgres
#    volumes:
#      - ./server/db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: server
    ports:
      - "5432:5432"


#  db:
#    image: postgres
#    restart: always
#    volumes:
#      - ./server/db:/var/lib/postgresql/data
#    environment:
#      POSTGRES_DB: "MoleDataBase"
#      POSTGRES_HOST_AUTH_METHOD: "trust"
#    container_name: postgres_db
#    ports:
#      - "5432:5432"
