version: "3.9"
services:
  app:
    build: .
    volumes:
      - .:/server
    ports:
      - 8000:8000

    environment:
      DB_HOST: ec2-52-19-188-149.eu-west-1.compute.amazonaws.com
      DB_NAME: daiqrnbks9gsvn
      DB_USER: yqnvckocyagpvc
      DB_PASS: 9b329f0b614045ddcb2545ebad5ae0176373e5cd94ed82036d5ea4749b73942d

    depends_on:
      - db
    image: application:django
    container_name: app_container
    command: >
      sh -c "python3 manage.py migrate &&
             python3 manage.py runserver"


  db:
    image: postgres:15.0-alpine
    container_name: MoleDataBase_postgres
#    volumes:
#      - ./server/db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: yqnvckocyagpvc
      POSTGRES_PASSWORD: 9b329f0b614045ddcb2545ebad5ae0176373e5cd94ed82036d5ea4749b73942d
      POSTGRES_DB: daiqrnbks9gsvn
    ports:
      - "5432:5432"


#  db:
#    image: postgres
#    restart: always
#    volumes:
#      - ./server/db:/var/lib/postgresql/data
#    environment:
#      POSTGRES_DB: "MoleDataBase"
#      POSTGRES_HOST_AUTH_METHOD: "trust"
#    container_name: postgres_db
#    ports:
#      - "5432:5432"
