# Generated by Django 4.1.2 on 2022-10-22 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('achievements', '0002_getachievements'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GetAchievements',
            new_name='UserAchievements',
        ),
    ]
